# Generated by Django 5.2.1 on 2025-05-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_bio_profile_birthdate_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram'),
        ),
    ]
