# Generated by Django 5.2.1 on 2025-05-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_profile_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Birthdate'),
        ),
    ]
