# Generated by Django 5.2.1 on 2025-05-18 21:46

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/fallback-profile-image.jpg', upload_to=dashboard.models.user_profile_image_path, verbose_name='Profile Image'),
        ),
    ]
